In [ ]:
from IPython.display import HTML
HTML('''
    <style> body {font-family: "Roboto Condensed Light", "Roboto Condensed";} h2 {padding: 10px 12px; background-color: #E64626; position: static; color: #ffffff; font-size: 40px;} .text_cell_render p { font-size: 15px; } .text_cell_render h1 { font-size: 30px; } h1 {padding: 10px 12px; background-color: #E64626; color: #ffffff; font-size: 40px;} .text_cell_render h3 { padding: 10px 12px; background-color: #0148A4; position: static; color: #ffffff; font-size: 20px;} h4:before{ 
    content: "@"; font-family:"Wingdings"; font-style:regular; margin-right: 4px;} .text_cell_render h4 {padding: 8px; font-family: "Roboto Condensed Light"; position: static; font-style: italic; background-color: #FFB800; color: #ffffff; font-size: 18px; text-align: center; border-radius: 5px;}input[type=submit] {background-color: #E64626; border: solid; border-color: #734036; color: white; padding: 8px 16px; text-decoration: none; margin: 4px 2px; cursor: pointer; border-radius: 20px;}</style>
''')

# Population

In [1]:
# Import necesary libraries
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
#Reading in the Data into a DataFrame, as it has no geometry info
relative_path = "Population.csv"
population_data = pd.read_csv(relative_path)
population_data.head(3)

,sa2_code,sa2_name,0-4_people,5-9_people,10-14_people,15-19_people,20-24_people,25-29_people,30-34_people,35-39_people,...,45-49_people,50-54_people,55-59_people,60-64_people,65-69_people,70-74_people,75-79_people,80-84_people,85-and-over_people,total_people
0,102011028,Avoca Beach - Copacabana,424,522,623,552,386,222,306,416,...,572,602,570,520,464,369,226,142,70,7530
1,102011029,Box Head - MacMasters Beach,511,666,702,592,461,347,420,535,...,749,749,794,895,863,925,603,331,264,11052
2,102011030,Calga - Kulnura,200,225,258,278,274,227,214,286,...,325,436,422,397,327,264,190,100,75,4748

The dataset claims the total population of NSW is ~5.26 million, which may or may not agree with nsw.gov.au, in saying 'NSW has the highest population of any state in Australia, with 8,153,000 residents as of 30 June 2022.' BUT 'Roughly 66% of the state's population live in Greater Sydney. Greater Sydney spans 55,000ha and includes metropolitan Sydney and surrounding areas up to and including the Central Coast, Blue Mountains, Wollondilly and Sutherland areas.'

Assuming our Dataset is focussed on the 'Greater Sydney Region' and not NSW, this is sufficiently close to correct.

In [5]:
sum(population_data.total_people)

5259764

In [9]:
#Create a list of all age range column names
age_ranges = []
for num in range(17):
    age_range = str(5*num) + '-' + str(5*num+4) + '_people'
    age_ranges.append(age_range)
age_ranges.append('85-and-over_people')
print(age_ranges)

['0-4_people', '5-9_people', '10-14_people', '15-19_people', '20-24_people', '25-29_people', '30-34_people', '35-39_people', '40-44_people', '45-49_people', '50-54_people', '55-59_people', '60-64_people', '65-69_people', '70-74_people', '75-79_people', '80-84_people', '85-and-over_people']

The Following code pieces are different tests for the presence of potential null values throughout the columns, all of which show that there are no null values.

In [19]:
#Check for explicit Null values in each column
for age in age_ranges:
    print(f'{age}, Null Values: {len(population_data[population_data[age].isnull()])}')

0-4_people, Null Values: 0
5-9_people, Null Values: 0
10-14_people, Null Values: 0
15-19_people, Null Values: 0
20-24_people, Null Values: 0
25-29_people, Null Values: 0
30-34_people, Null Values: 0
35-39_people, Null Values: 0
40-44_people, Null Values: 0
45-49_people, Null Values: 0
50-54_people, Null Values: 0
55-59_people, Null Values: 0
60-64_people, Null Values: 0
65-69_people, Null Values: 0
70-74_people, Null Values: 0
75-79_people, Null Values: 0
80-84_people, Null Values: 0
85-and-over_people, Null Values: 0

In [20]:
#Check for negative entries
for age in age_ranges:
    print(f'{age}, Negative Values: {len(population_data[population_data[age] < 0])}')

0-4_people, Negative Values: 0
5-9_people, Negative Values: 0
10-14_people, Negative Values: 0
15-19_people, Negative Values: 0
20-24_people, Negative Values: 0
25-29_people, Negative Values: 0
30-34_people, Negative Values: 0
35-39_people, Negative Values: 0
40-44_people, Negative Values: 0
45-49_people, Negative Values: 0
50-54_people, Negative Values: 0
55-59_people, Negative Values: 0
60-64_people, Negative Values: 0
65-69_people, Negative Values: 0
70-74_people, Negative Values: 0
75-79_people, Negative Values: 0
80-84_people, Negative Values: 0
85-and-over_people, Negative Values: 0

The next test is to determine whether all the sums of population for each area is correct, and the result of an empty dataframe means that it is correct.

In [37]:
# Calculate the total population from each row
calc_population = population_data[age_ranges].sum(axis=1, numeric_only=True) #Using population_data[age_ranges] to remove sa2_code which would otherwise be added.
population_data['total_people_calc'] = calc_population
population_data[population_data['total_people'] != population_data['total_people_calc']]

Empty DataFrame
Columns: [sa2_code, sa2_name, 0-4_people, 5-9_people, 10-14_people, 15-19_people, 20-24_people, 25-29_people, 30-34_people, 35-39_people, 40-44_people, 45-49_people, 50-54_people, 55-59_people, 60-64_people, 65-69_people, 70-74_people, 75-79_people, 80-84_people, 85-and-over_people, total_people, total_people_calc]
Index: []

[0 rows x 22 columns]

In [42]:
population_data['sa2_code']

0      102011028
1      102011029
2      102011030
3      102011031
4      102011032
         ...
368    128021537
369    128021538
370    128021607
371    128021608
372    128021609
Name: sa2_code, Length: 373, dtype: int64